-- Rollback 000017: restore routes linkage and remove itinerary split table

CREATE TABLE IF NOT EXISTS routes (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  status SMALLINT DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO routes (id, code, name, description, status)
VALUES (1, 'RESTORED-DEFAULT', 'Restored Default Route', 'autogenerated rollback route', 1)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE voyages
  ADD COLUMN IF NOT EXISTS route_id BIGINT;

UPDATE voyages
SET route_id = 1
WHERE route_id IS NULL;

ALTER TABLE voyages
  ALTER COLUMN route_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'voyages_route_id_fkey'
  ) THEN
    ALTER TABLE voyages
      ADD CONSTRAINT voyages_route_id_fkey FOREIGN KEY (route_id) REFERENCES routes(id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_voyages_route_id ON voyages(route_id);

ALTER TABLE voyages
  DROP COLUMN IF EXISTS brief_info;

ALTER TABLE voyages
  DROP CONSTRAINT IF EXISTS chk_voyages_return_after_depart;

DROP TABLE IF EXISTS voyage_itineraries;
