DROP TABLE IF EXISTS order_status_logs CASCADE;
DROP TABLE IF EXISTS notification_templates CASCADE;
DROP TABLE IF EXISTS shop_info CASCADE;
DROP TABLE IF EXISTS refund_rules CASCADE;
DROP TABLE IF EXISTS reconciliations CASCADE;
DROP TABLE IF EXISTS operation_logs CASCADE;
ALTER TABLE staffs DROP COLUMN IF EXISTS role;
