DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS staffs CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS facilities CASCADE;
DROP TABLE IF EXISTS facility_categories CASCADE;
DROP TABLE IF EXISTS cabin_types CASCADE;
DROP TABLE IF EXISTS cruises CASCADE;
DROP TABLE IF EXISTS cruise_companies CASCADE;
